example1

diff --git a/.github/workflows/01-building-blocks.yml b/.github/workflows/01-building-blocks.yml
--- a/.github/workflows/01-building-blocks.yml
+++ b/.github/workflows/01-building-blocks.yml
@@ -9,5 +9,9 @@ jobs:
   echo-goodbye:
     runs-on: ubuntu-latest
     steps:
+      - name: Failed step!!
+        run: |
+            echo "I will fail now"
+            exit 1
       - name: Say Goodbye
         run: echo "Goodbye, World!"
